import type { Destination, Flight, Hotel, TripPackage } from './types';

export const sampleDestinations: Destination[] = [
  {
    id: "dest-1",
    name: "Paris, France",
    description: "The City of Light offers iconic landmarks, world-class museums, and romantic ambiance.",
    image: "https://images.unsplash.com/photo-1502602898536-47ad22581b52?w=800&h=600&fit=crop",
    country: "France",
    continent: "Europe",
    rating: 4.8,
    priceRange: "$$$",
    bestTimeToVisit: "April to October",
    highlights: ["Eiffel Tower", "Louvre Museum", "Notre-Dame Cathedral", "Champs-Élysées"],
    createdAt: new Date("2024-01-01")
  },
  {
    id: "dest-2",
    name: "Tokyo, Japan",
    description: "A fascinating blend of ultramodern and traditional, offering unique cultural experiences.",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=600&fit=crop",
    country: "Japan",
    continent: "Asia",
    rating: 4.9,
    priceRange: "$$$",
    bestTimeToVisit: "March to May and September to November",
    highlights: ["Shibuya Crossing", "Senso-ji Temple", "Tokyo Skytree", "Tsukiji Market"],
    createdAt: new Date("2024-01-01")
  },
  {
    id: "dest-3",
    name: "New York City, USA",
    description: "The Big Apple offers world-famous attractions, diverse neighborhoods, and endless entertainment.",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&h=600&fit=crop",
    country: "USA",
    continent: "North America",
    rating: 4.7,
    priceRange: "$$$",
    bestTimeToVisit: "April to June and September to November",
    highlights: ["Times Square", "Central Park", "Statue of Liberty", "Broadway"],
    createdAt: new Date("2024-01-01")
  },
  {
    id: "dest-4",
    name: "Sydney, Australia",
    description: "A stunning harbor city with beautiful beaches, iconic landmarks, and a laid-back lifestyle.",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&h=600&fit=crop",
    country: "Australia",
    continent: "Oceania",
    rating: 4.6,
    priceRange: "$$$",
    bestTimeToVisit: "September to November and March to May",
    highlights: ["Sydney Opera House", "Bondi Beach", "Harbor Bridge", "Royal Botanic Garden"],
    createdAt: new Date("2024-01-01")
  },
  {
    id: "dest-5",
    name: "Cape Town, South Africa",
    description: "A beautiful coastal city with stunning natural landscapes and rich cultural heritage.",
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&h=600&fit=crop",
    country: "South Africa",
    continent: "Africa",
    rating: 4.5,
    priceRange: "$$",
    bestTimeToVisit: "March to May and September to November",
    highlights: ["Table Mountain", "Robben Island", "V&A Waterfront", "Cape Point"],
    createdAt: new Date("2024-01-01")
  },
  {
    id: "dest-6",
    name: "Rio de Janeiro, Brazil",
    description: "A vibrant city known for its stunning beaches, carnival celebrations, and iconic landmarks.",
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&h=600&fit=crop",
    country: "Brazil",
    continent: "South America",
    rating: 4.4,
    priceRange: "$$",
    bestTimeToVisit: "March to May and September to November",
    highlights: ["Christ the Redeemer", "Copacabana Beach", "Sugarloaf Mountain", "Ipanema"],
    createdAt: new Date("2024-01-01")
  }
];

export const samplePackages: TripPackage[] = [
  {
    id: "pkg-1",
    name: "Paris Romance Package",
    description: "Experience the magic of Paris with this romantic 7-day package including luxury accommodations and guided tours.",
    image: "https://images.unsplash.com/photo-1502602898536-47ad22581b52?w=800&h=600&fit=crop",
    destinationId: "dest-1",
    duration: 7,
    price: 2499,
    currency: "USD",
    category: "romance",
    includes: ["Luxury hotel accommodation", "Daily breakfast", "Guided city tours", "Eiffel Tower visit", "Seine River cruise"],
    highlights: ["Eiffel Tower dinner", "Louvre Museum tour", "Montmartre exploration", "Champagne tasting"],
    createdAt: new Date("2024-01-01")
  },
  {
    id: "pkg-2",
    name: "Tokyo Adventure",
    description: "Discover the fascinating culture and technology of Tokyo with this comprehensive 10-day adventure package.",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=600&fit=crop",
    destinationId: "dest-2",
    duration: 10,
    price: 3299,
    currency: "USD",
    category: "adventure",
    includes: ["Boutique hotel accommodation", "Daily breakfast", "Cultural workshops", "Bullet train experience", "Local guide"],
    highlights: ["Sushi making class", "Mount Fuji day trip", "Traditional tea ceremony", "Akihabara tech tour"],
    createdAt: new Date("2024-01-01")
  },
  {
    id: "pkg-3",
    name: "NYC City Break",
    description: "Experience the energy of New York City with this action-packed 5-day city break package.",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&h=600&fit=crop",
    destinationId: "dest-3",
    duration: 5,
    price: 1899,
    currency: "USD",
    category: "city-break",
    includes: ["Central hotel accommodation", "Daily breakfast", "Broadway show ticket", "City pass", "Airport transfers"],
    highlights: ["Broadway show", "Empire State Building", "Central Park tour", "Brooklyn Bridge walk"],
    createdAt: new Date("2024-01-01")
  },
  {
    id: "pkg-4",
    name: "Sydney Coastal Escape",
    description: "Relax and explore the beautiful coastal city of Sydney with this 8-day escape package.",
    image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800&h=600&fit=crop",
    destinationId: "dest-4",
    duration: 8,
    price: 2799,
    currency: "USD",
    category: "beach",
    includes: ["Harbor view hotel", "Daily breakfast", "Opera House tour", "Bondi Beach day", "Blue Mountains trip"],
    highlights: ["Sydney Opera House performance", "Bondi to Bronte coastal walk", "Taronga Zoo visit", "Harbor dinner cruise"],
    createdAt: new Date("2024-01-01")
  },
  {
    id: "pkg-5",
    name: "Cape Town Explorer",
    description: "Discover the natural beauty and rich history of Cape Town with this comprehensive 9-day exploration package.",
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800&h=600&fit=crop",
    destinationId: "dest-5",
    duration: 9,
    price: 2199,
    currency: "USD",
    category: "nature",
    includes: ["Boutique hotel accommodation", "Daily breakfast", "Table Mountain cable car", "Robben Island tour", "Wine tasting"],
    highlights: ["Table Mountain sunset", "Cape Point visit", "Wine region tour", "Penguin colony visit"],
    createdAt: new Date("2024-01-01")
  },
  {
    id: "pkg-6",
    name: "Rio Carnival Experience",
    description: "Immerse yourself in the vibrant culture of Rio de Janeiro with this 6-day carnival experience package.",
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&h=600&fit=crop",
    destinationId: "dest-6",
    duration: 6,
    price: 1899,
    currency: "USD",
    category: "culture",
    includes: ["Beachfront hotel", "Daily breakfast", "Carnival parade tickets", "Samba lesson", "Local guide"],
    highlights: ["Carnival parade", "Christ the Redeemer visit", "Copacabana Beach day", "Favela tour"],
    createdAt: new Date("2024-01-01")
  }
];

export const sampleFlights: Flight[] = [
  {
    id: "flight-1",
    airline: "Air France",
    flightNumber: "AF123",
    from: "New York",
    to: "Paris",
    departureTime: "2024-06-15T10:00:00Z",
    arrivalTime: "2024-06-16T09:30:00Z",
    price: 899,
    currency: "USD",
    class: "economy",
    stops: 0,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "flight-2",
    airline: "Japan Airlines",
    flightNumber: "JL456",
    from: "Los Angeles",
    to: "Tokyo",
    departureTime: "2024-06-20T14:30:00Z",
    arrivalTime: "2024-06-21T18:45:00Z",
    price: 1299,
    currency: "USD",
    class: "economy",
    stops: 0,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "flight-3",
    airline: "Delta Airlines",
    flightNumber: "DL789",
    from: "London",
    to: "New York",
    departureTime: "2024-06-25T08:15:00Z",
    arrivalTime: "2024-06-25T11:30:00Z",
    price: 699,
    currency: "USD",
    class: "economy",
    stops: 0,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "flight-4",
    airline: "Qantas",
    flightNumber: "QF101",
    from: "Los Angeles",
    to: "Sydney",
    departureTime: "2024-07-01T22:00:00Z",
    arrivalTime: "2024-07-03T06:30:00Z",
    price: 1499,
    currency: "USD",
    class: "economy",
    stops: 0,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "flight-5",
    airline: "South African Airways",
    flightNumber: "SA234",
    from: "London",
    to: "Cape Town",
    departureTime: "2024-07-10T20:30:00Z",
    arrivalTime: "2024-07-11T08:15:00Z",
    price: 1099,
    currency: "USD",
    class: "economy",
    stops: 0,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "flight-6",
    airline: "LATAM",
    flightNumber: "LA567",
    from: "Miami",
    to: "Rio de Janeiro",
    departureTime: "2024-07-15T16:45:00Z",
    arrivalTime: "2024-07-16T04:30:00Z",
    price: 799,
    currency: "USD",
    class: "economy",
    stops: 0,
    createdAt: new Date("2024-01-01")
  }
];

export const sampleHotels: Hotel[] = [
  {
    id: "hotel-1",
    name: "Le Grand Hotel Paris",
    location: "Paris, France",
    description: "Luxury 5-star hotel in the heart of Paris with stunning Eiffel Tower views.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop",
    rating: 4.8,
    pricePerNight: 450,
    currency: "USD",
    amenities: ["Free WiFi", "Spa", "Restaurant", "Room Service", "Gym", "Pool"],
    distanceFromCenter: 0.5,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "hotel-2",
    name: "Tokyo Tower Hotel",
    location: "Tokyo, Japan",
    description: "Modern hotel with panoramic city views and easy access to major attractions.",
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop",
    rating: 4.7,
    pricePerNight: 380,
    currency: "USD",
    amenities: ["Free WiFi", "Restaurant", "Bar", "Business Center", "Concierge"],
    distanceFromCenter: 1.2,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "hotel-3",
    name: "Manhattan Central Hotel",
    location: "New York City, USA",
    description: "Boutique hotel in the heart of Manhattan with easy access to Times Square.",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop",
    rating: 4.6,
    pricePerNight: 320,
    currency: "USD",
    amenities: ["Free WiFi", "Restaurant", "Fitness Center", "Concierge", "Valet Parking"],
    distanceFromCenter: 0.3,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "hotel-4",
    name: "Sydney Harbor View Hotel",
    location: "Sydney, Australia",
    description: "Luxury hotel with stunning harbor views and close proximity to the Opera House.",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop",
    rating: 4.9,
    pricePerNight: 520,
    currency: "USD",
    amenities: ["Free WiFi", "Spa", "Restaurant", "Pool", "Gym", "Harbor View"],
    distanceFromCenter: 0.8,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "hotel-5",
    name: "Cape Town Mountain Lodge",
    location: "Cape Town, South Africa",
    description: "Boutique lodge with spectacular mountain views and personalized service.",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop",
    rating: 4.5,
    pricePerNight: 280,
    currency: "USD",
    amenities: ["Free WiFi", "Restaurant", "Mountain View", "Garden", "Concierge"],
    distanceFromCenter: 2.1,
    createdAt: new Date("2024-01-01")
  },
  {
    id: "hotel-6",
    name: "Rio Beach Resort",
    location: "Rio de Janeiro, Brazil",
    description: "Beachfront resort with direct access to Copacabana Beach and stunning ocean views.",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&h=600&fit=crop",
    rating: 4.4,
    pricePerNight: 350,
    currency: "USD",
    amenities: ["Free WiFi", "Beach Access", "Pool", "Restaurant", "Spa", "Gym"],
    distanceFromCenter: 1.5,
    createdAt: new Date("2024-01-01")
  }
];
